DECLARE @StartDT DATE ='20150101'
DECLARE @EndDT DATE ='20151231'

;WITH Cte AS
(
SELECT 1 WeekNo,DATEADD(WEEK,DATEDIFF(WEEK,0,'20150101'),0) StartDT
UNION ALL
SELECT WeekNo+1,DATEADD(WEEK,1,StartDt) FROM Cte
WHERE WeekNo<=DATEDIFF(WEEK,@StartDT,@EndDT)
)
SELECT 'Week No.'+LTRIM(STR(WeekNo)) WeekNo,CONVERT(VARCHAR,StartDT,106) StartDT,CONVERT(VARCHAR,DATEADD(DAY,6,StartDt),106) EndDT FROM CTE
OPTION(MAXRECURSION 0)